"""Site text in English, German, Russian and Latvian.

Category names, specification labels and interface strings live here so the
build script only deals with layout. Edit wording here, then run build.py.
"""

LANGS = ["en", "de", "ru", "lv"]
LANG_NAMES = {"en": "English", "de": "Deutsch", "ru": "Русский", "lv": "Latviešu"}
OG_LOCALE = {"en": "en_GB", "de": "de_DE", "ru": "ru_RU", "lv": "lv_LV"}

COMPANY = {
    "name": "Trimen Tractors",
    "legal": "AS Trimen Tractors",
    "reg": "40003638330",
    "vat": "LV40003638330",
    "phone": "+371 67247977",
    "street": "“Valodzes”, Klīves",
    "parish": "Babītes pag.",
    "municipality": "Mārupes nov.",
    "postcode": "LV-2107",
    "lat": 56.907551,
    "lng": 23.776744,
    "facebook": "https://www.facebook.com/trimentractors",
    "twitter": "https://twitter.com/TrimenTractors",
    "banks": [
        ("Citadele banka AS", "PARXLV22", "LV40PARX0006608340001"),
        ("Luminor Bank AS", "RIKOLV2X", "LV73RIKO0000082468288"),
    ],
}
COUNTRY = {"en": "Latvia", "de": "Lettland", "ru": "Латвия", "lv": "Latvija"}

# Page slugs that are not categories.
PAGE_SLUGS = {
    "stock": {"en": "stock", "de": "angebote", "ru": "katalog", "lv": "piedavajumi"},
    "about": {"en": "about-us", "de": "ueber-uns", "ru": "o-nas", "lv": "par-mums"},
}

GROUPS = {
    0: {
        "slug": {"en": "machinery", "de": "maschinen", "ru": "tekhnika", "lv": "tehnika"},
        "name": {"en": "Machinery", "de": "Maschinen", "ru": "Техника", "lv": "Tehnika"},
        "h1": {
            "en": "Used construction and farm machinery",
            "de": "Gebrauchte Bau- und Landmaschinen",
            "ru": "Б/у строительная и сельскохозяйственная техника",
            "lv": "Lietota būvtehnika un lauksaimniecības tehnika",
        },
        "intro": {
            "en": "Used construction, agricultural and forestry machinery from our stock in Klīves, Latvia.",
            "de": "Gebrauchte Bau-, Land- und Forstmaschinen aus unserem Bestand in Klīves, Lettland.",
            "ru": "Б/у строительная, сельскохозяйственная и лесная техника в наличии на нашей площадке под Ригой.",
            "lv": "Lietota būvtehnika, lauksaimniecības un meža tehnika no mūsu laukuma Klīvēs.",
        },
    },
    1: {
        "slug": {"en": "trucks", "de": "lkw", "ru": "gruzoviki", "lv": "kravas-auto"},
        "name": {"en": "Trucks", "de": "Lkw", "ru": "Грузовики", "lv": "Kravas auto"},
        "h1": {
            "en": "Used trucks",
            "de": "Gebrauchte Lkw",
            "ru": "Б/у грузовики",
            "lv": "Lietoti kravas auto",
        },
        "intro": {
            "en": "Used tractor units, tippers and other trucks from our stock in Klīves, Latvia.",
            "de": "Gebrauchte Sattelzugmaschinen, Kipper und andere Lkw aus unserem Bestand in Klīves, Lettland.",
            "ru": "Б/у седельные тягачи, самосвалы и другие грузовики в наличии на нашей площадке под Ригой.",
            "lv": "Lietoti vilcēji, pašizgāzēji un citi kravas auto no mūsu laukuma Klīvēs.",
        },
    },
    2: {
        "slug": {"en": "work-tools", "de": "anbaugeraete", "ru": "navesnoe-oborudovanie", "lv": "darba-aprikojums"},
        "name": {"en": "Work tools", "de": "Anbaugeräte", "ru": "Навесное оборудование", "lv": "Darba aprīkojums"},
        "h1": {
            "en": "Buckets, quick couplers and work tools",
            "de": "Löffel, Schnellwechsler und Anbaugeräte",
            "ru": "Ковши, быстросъемы и навесное оборудование",
            "lv": "Kausi, ātrās sakabes un darba aprīkojums",
        },
        "intro": {
            "en": "Excavator and wheel loader buckets, quick couplers, hammers, grapples and other work tools in stock in Klīves, Latvia.",
            "de": "Tieflöffel, Radladerschaufeln, Schnellwechsler, Hämmer, Greifer und weitere Anbaugeräte aus unserem Bestand in Klīves, Lettland.",
            "ru": "Ковши для экскаваторов и фронтальных погрузчиков, быстросъемы, гидромолоты, грейферы и другое навесное оборудование в наличии на нашей площадке под Ригой.",
            "lv": "Ekskavatoru un frontālo iekrāvēju kausi, ātrās sakabes, hidroāmuri, greiferi un cits darba aprīkojums no mūsu laukuma Klīvēs.",
        },
    },
}

# id: slug, plural name, singular noun, page heading. The ids are the old site's category ids.
CATEGORIES = {
    2: {"slug": {"en": "dozers", "de": "planierraupen", "ru": "buldozery", "lv": "buldozeri"},
        "name": {"en": "Dozers", "de": "Planierraupen", "ru": "Бульдозеры", "lv": "Buldozeri"},
        "one": {"en": "dozer", "de": "Planierraupe", "ru": "бульдозер", "lv": "buldozers"},
        "h1": {"en": "Used dozers", "de": "Gebrauchte Planierraupen", "ru": "Б/у бульдозеры", "lv": "Lietoti buldozeri"}},
    11: {"slug": {"en": "wheel-loaders", "de": "radlader", "ru": "frontalnye-pogruzchiki", "lv": "frontalie-iekraveji"},
         "name": {"en": "Wheel loaders", "de": "Radlader", "ru": "Фронтальные погрузчики", "lv": "Frontālie iekrāvēji"},
         "one": {"en": "wheel loader", "de": "Radlader", "ru": "фронтальный погрузчик", "lv": "frontālais iekrāvējs"},
         "h1": {"en": "Used wheel loaders", "de": "Gebrauchte Radlader", "ru": "Б/у фронтальные погрузчики", "lv": "Lietoti frontālie iekrāvēji"}},
    12: {"slug": {"en": "backhoe-loaders", "de": "baggerlader", "ru": "ekskavatory-pogruzchiki", "lv": "ekskavatori-iekraveji"},
         "name": {"en": "Backhoe loaders", "de": "Baggerlader", "ru": "Экскаваторы-погрузчики", "lv": "Ekskavatori-iekrāvēji"},
         "one": {"en": "backhoe loader", "de": "Baggerlader", "ru": "экскаватор-погрузчик", "lv": "ekskavators-iekrāvējs"},
         "h1": {"en": "Used backhoe loaders", "de": "Gebrauchte Baggerlader", "ru": "Б/у экскаваторы-погрузчики", "lv": "Lietoti ekskavatori-iekrāvēji"}},
    14: {"slug": {"en": "tracked-excavators", "de": "kettenbagger", "ru": "gusenichnye-ekskavatory", "lv": "kapurkezu-ekskavatori"},
         "name": {"en": "Tracked excavators", "de": "Kettenbagger", "ru": "Гусеничные экскаваторы", "lv": "Kāpurķēžu ekskavatori"},
         "one": {"en": "tracked excavator", "de": "Kettenbagger", "ru": "гусеничный экскаватор", "lv": "kāpurķēžu ekskavators"},
         "h1": {"en": "Used tracked excavators", "de": "Gebrauchte Kettenbagger", "ru": "Б/у гусеничные экскаваторы", "lv": "Lietoti kāpurķēžu ekskavatori"}},
    15: {"slug": {"en": "wheel-excavators", "de": "mobilbagger", "ru": "kolesnye-ekskavatory", "lv": "ritenu-ekskavatori"},
         "name": {"en": "Wheel excavators", "de": "Mobilbagger", "ru": "Колесные экскаваторы", "lv": "Riteņu ekskavatori"},
         "one": {"en": "wheel excavator", "de": "Mobilbagger", "ru": "колесный экскаватор", "lv": "riteņu ekskavators"},
         "h1": {"en": "Used wheel excavators", "de": "Gebrauchte Mobilbagger", "ru": "Б/у колесные экскаваторы", "lv": "Lietoti riteņu ekskavatori"}},
    17: {"slug": {"en": "telehandlers", "de": "teleskoplader", "ru": "teleskopicheskie-pogruzchiki", "lv": "teleskopiskie-iekraveji"},
         "name": {"en": "Telehandlers", "de": "Teleskoplader", "ru": "Телескопические погрузчики", "lv": "Teleskopiskie iekrāvēji"},
         "one": {"en": "telehandler", "de": "Teleskoplader", "ru": "телескопический погрузчик", "lv": "teleskopiskais iekrāvējs"},
         "h1": {"en": "Used telehandlers", "de": "Gebrauchte Teleskoplader", "ru": "Б/у телескопические погрузчики", "lv": "Lietoti teleskopiskie iekrāvēji"}},
    18: {"slug": {"en": "skid-steer-loaders", "de": "kompaktlader", "ru": "mini-pogruzchiki", "lv": "kompaktie-iekraveji"},
         "name": {"en": "Skid steer loaders", "de": "Kompaktlader", "ru": "Мини-погрузчики", "lv": "Kompaktie iekrāvēji"},
         "one": {"en": "skid steer loader", "de": "Kompaktlader", "ru": "мини-погрузчик", "lv": "kompaktais iekrāvējs"},
         "h1": {"en": "Used skid steer loaders", "de": "Gebrauchte Kompaktlader", "ru": "Б/у мини-погрузчики", "lv": "Lietoti kompaktie iekrāvēji"}},
    21: {"slug": {"en": "pavers", "de": "asphaltfertiger", "ru": "asfaltoukladchiki", "lv": "asfalta-ieklajeji"},
         "name": {"en": "Pavers", "de": "Asphaltfertiger", "ru": "Асфальтоукладчики", "lv": "Asfalta ieklājēji"},
         "one": {"en": "paver", "de": "Asphaltfertiger", "ru": "асфальтоукладчик", "lv": "asfalta ieklājējs"},
         "h1": {"en": "Used asphalt pavers", "de": "Gebrauchte Asphaltfertiger", "ru": "Б/у асфальтоукладчики", "lv": "Lietoti asfalta ieklājēji"}},
    20: {"slug": {"en": "rollers", "de": "walzen", "ru": "katki", "lv": "veltni"},
         "name": {"en": "Rollers", "de": "Walzen", "ru": "Катки", "lv": "Veltņi"},
         "one": {"en": "roller", "de": "Walze", "ru": "каток", "lv": "veltnis"},
         "h1": {"en": "Used rollers", "de": "Gebrauchte Walzen", "ru": "Б/у катки", "lv": "Lietoti veltņi"}},
    22: {"slug": {"en": "graders", "de": "grader", "ru": "avtogreydery", "lv": "greideri"},
         "name": {"en": "Graders", "de": "Grader", "ru": "Автогрейдеры", "lv": "Greideri"},
         "one": {"en": "grader", "de": "Grader", "ru": "автогрейдер", "lv": "greideris"},
         "h1": {"en": "Used graders", "de": "Gebrauchte Grader", "ru": "Б/у автогрейдеры", "lv": "Lietoti greideri"}},
    31: {"slug": {"en": "dumpers", "de": "dumper", "ru": "dumpery", "lv": "pasizgazeji"},
         "name": {"en": "Dumpers", "de": "Dumper", "ru": "Думперы", "lv": "Pašizgāzēji"},
         "one": {"en": "dumper", "de": "Dumper", "ru": "думпер", "lv": "pašizgāzējs"},
         "h1": {"en": "Used dumpers", "de": "Gebrauchte Dumper", "ru": "Б/у думперы", "lv": "Lietoti pašizgāzēji"}},
    19: {"slug": {"en": "forklifts", "de": "gabelstapler", "ru": "vilochnye-pogruzchiki", "lv": "daksu-iekraveji"},
         "name": {"en": "Forklifts", "de": "Gabelstapler", "ru": "Вилочные погрузчики", "lv": "Dakšu iekrāvēji"},
         "one": {"en": "forklift", "de": "Gabelstapler", "ru": "вилочный погрузчик", "lv": "dakšu iekrāvējs"},
         "h1": {"en": "Used forklifts", "de": "Gebrauchte Gabelstapler", "ru": "Б/у вилочные погрузчики", "lv": "Lietoti dakšu iekrāvēji"}},
    13: {"slug": {"en": "forestry-machines", "de": "forstmaschinen", "ru": "lesnaya-tekhnika", "lv": "meza-tehnika"},
         "name": {"en": "Forestry machines", "de": "Forstmaschinen", "ru": "Лесная техника", "lv": "Meža tehnika"},
         "one": {"en": "forestry machine", "de": "Forstmaschine", "ru": "лесная машина", "lv": "meža mašīna"},
         "h1": {"en": "Used forestry machines", "de": "Gebrauchte Forstmaschinen", "ru": "Б/у лесная техника", "lv": "Lietota meža tehnika"}},
    16: {"slug": {"en": "agricultural-machinery", "de": "landmaschinen", "ru": "selkhoztekhnika", "lv": "lauksaimniecibas-tehnika"},
         "name": {"en": "Agricultural machinery", "de": "Landmaschinen", "ru": "Сельхозтехника", "lv": "Lauksaimniecības tehnika"},
         "one": {"en": "agricultural machine", "de": "Landmaschine", "ru": "сельхозмашина", "lv": "lauksaimniecības mašīna"},
         "h1": {"en": "Used agricultural machinery", "de": "Gebrauchte Landmaschinen", "ru": "Б/у сельхозтехника", "lv": "Lietota lauksaimniecības tehnika"}},
    30: {"slug": {"en": "other-machinery", "de": "sonstige-maschinen", "ru": "drugaya-tekhnika", "lv": "cita-tehnika"},
         "name": {"en": "Other machinery", "de": "Sonstige Maschinen", "ru": "Другая техника", "lv": "Cita tehnika"},
         "one": {"en": "machine", "de": "Maschine", "ru": "техника", "lv": "tehnika"},
         "h1": {"en": "Other used machinery", "de": "Sonstige gebrauchte Maschinen", "ru": "Другая б/у техника", "lv": "Cita lietota tehnika"}},
    24: {"slug": {"en": "tractor-units", "de": "sattelzugmaschinen", "ru": "sedelnye-tyagachi", "lv": "vilceji"},
         "name": {"en": "Tractor units", "de": "Sattelzugmaschinen", "ru": "Седельные тягачи", "lv": "Vilcēji"},
         "one": {"en": "tractor unit", "de": "Sattelzugmaschine", "ru": "седельный тягач", "lv": "vilcējs"},
         "h1": {"en": "Used tractor units", "de": "Gebrauchte Sattelzugmaschinen", "ru": "Б/у седельные тягачи", "lv": "Lietoti vilcēji"}},
    25: {"slug": {"en": "tippers-and-crane-trucks", "de": "kipper-und-kran-lkw", "ru": "samosvaly-i-manipulyatory", "lv": "kravas-pasizgazeji-un-manipulatori"},
         "name": {"en": "Tippers and crane trucks", "de": "Kipper und Kran-Lkw", "ru": "Самосвалы и манипуляторы", "lv": "Kravas pašizgāzēji un manipulatori"},
         "one": {"en": "tipper truck", "de": "Kipper", "ru": "самосвал", "lv": "kravas pašizgāzējs"},
         "h1": {"en": "Used tippers and crane trucks", "de": "Gebrauchte Kipper und Kran-Lkw", "ru": "Б/у самосвалы и манипуляторы", "lv": "Lietoti kravas pašizgāzēji un manipulatori"}},
    26: {"slug": {"en": "trucks-up-to-7-5-t", "de": "lkw-bis-7-5-t", "ru": "gruzoviki-do-7-5-t", "lv": "kravas-auto-lidz-7-5-t"},
         "name": {"en": "Trucks up to 7.5 t", "de": "Lkw bis 7,5 t", "ru": "Грузовики до 7,5 т", "lv": "Kravas auto līdz 7,5 t"},
         "one": {"en": "truck", "de": "Lkw", "ru": "грузовик", "lv": "kravas auto"},
         "h1": {"en": "Used trucks up to 7.5 t", "de": "Gebrauchte Lkw bis 7,5 t", "ru": "Б/у грузовики до 7,5 т", "lv": "Lietoti kravas auto līdz 7,5 t"}},
    27: {"slug": {"en": "trucks-over-7-5-t", "de": "lkw-ueber-7-5-t", "ru": "gruzoviki-svyshe-7-5-t", "lv": "kravas-auto-virs-7-5-t"},
         "name": {"en": "Trucks over 7.5 t", "de": "Lkw über 7,5 t", "ru": "Грузовики свыше 7,5 т", "lv": "Kravas auto virs 7,5 t"},
         "one": {"en": "truck", "de": "Lkw", "ru": "грузовик", "lv": "kravas auto"},
         "h1": {"en": "Used trucks over 7.5 t", "de": "Gebrauchte Lkw über 7,5 t", "ru": "Б/у грузовики свыше 7,5 т", "lv": "Lietoti kravas auto virs 7,5 t"}},
    33: {"slug": {"en": "semi-trailers", "de": "sattelauflieger", "ru": "polupritsepy", "lv": "puspiekabes"},
         "name": {"en": "Semi-trailers", "de": "Sattelauflieger", "ru": "Полуприцепы", "lv": "Puspiekabes"},
         "one": {"en": "semi-trailer", "de": "Sattelauflieger", "ru": "полуприцеп", "lv": "puspiekabe"},
         "h1": {"en": "Used semi-trailers", "de": "Gebrauchte Sattelauflieger", "ru": "Б/у полуприцепы", "lv": "Lietotas puspiekabes"}},
    28: {"slug": {"en": "vans", "de": "transporter", "ru": "furgony-i-mikroavtobusy", "lv": "mikroautobusi"},
         "name": {"en": "Vans", "de": "Transporter", "ru": "Фургоны и микроавтобусы", "lv": "Mikroautobusi"},
         "one": {"en": "van", "de": "Transporter", "ru": "фургон", "lv": "mikroautobuss"},
         "h1": {"en": "Used vans", "de": "Gebrauchte Transporter", "ru": "Б/у фургоны и микроавтобусы", "lv": "Lietoti mikroautobusi"}},
    29: {"slug": {"en": "cars", "de": "pkw", "ru": "legkovye-avtomobili", "lv": "vieglie-auto"},
         "name": {"en": "Cars", "de": "Pkw", "ru": "Легковые автомобили", "lv": "Vieglie auto"},
         "one": {"en": "car", "de": "Pkw", "ru": "легковой автомобиль", "lv": "vieglais auto"},
         "h1": {"en": "Used cars", "de": "Gebrauchte Pkw", "ru": "Б/у легковые автомобили", "lv": "Lietoti vieglie auto"}},
    36: {"slug": {"en": "excavator-buckets", "de": "tiefloeffel", "ru": "ekskavatornye-kovshi", "lv": "rokamie-kausi"},
         "name": {"en": "Excavator buckets", "de": "Tieflöffel", "ru": "Экскаваторные ковши", "lv": "Rokamie kausi"},
         "one": {"en": "excavator bucket", "de": "Tieflöffel", "ru": "экскаваторный ковш", "lv": "rokamais kauss"}},
    37: {"slug": {"en": "ditch-cleaning-buckets", "de": "grabenraeumloeffel", "ru": "planirovochnye-kovshi", "lv": "planejamie-kausi"},
         "name": {"en": "Ditch cleaning buckets", "de": "Grabenräumlöffel", "ru": "Планировочные ковши", "lv": "Planējamie kausi"},
         "one": {"en": "ditch cleaning bucket", "de": "Grabenräumlöffel", "ru": "планировочный ковш", "lv": "planējamais kauss"}},
    38: {"slug": {"en": "wheel-loader-buckets", "de": "radladerschaufeln", "ru": "kovshi-dlya-frontalnykh-pogruzchikov", "lv": "frontalo-iekraveju-kausi"},
         "name": {"en": "Wheel loader buckets", "de": "Radladerschaufeln", "ru": "Ковши для фронтальных погрузчиков", "lv": "Frontālo iekrāvēju kausi"},
         "one": {"en": "wheel loader bucket", "de": "Radladerschaufel", "ru": "ковш для фронтального погрузчика", "lv": "frontālā iekrāvēja kauss"}},
    40: {"slug": {"en": "quick-couplers", "de": "schnellwechsler", "ru": "bystrosemy", "lv": "atras-sakabes"},
         "name": {"en": "Quick couplers", "de": "Schnellwechsler", "ru": "Быстросъемы", "lv": "Ātrās sakabes"},
         "one": {"en": "quick coupler", "de": "Schnellwechsler", "ru": "быстросъем", "lv": "ātrā sakabe"}},
    39: {"slug": {"en": "shears-hammers-grapples", "de": "scheren-haemmer-greifer", "ru": "nozhnitsy-gidromoloty-greyfery", "lv": "skeres-hidroamuri-satvereji"},
         "name": {"en": "Shears, hammers and grapples", "de": "Scheren, Hämmer und Greifer", "ru": "Ножницы, гидромолоты и грейферы", "lv": "Šķēres, hidroāmuri un satvērēji"},
         "one": {"en": "attachment", "de": "Anbaugerät", "ru": "навесное оборудование", "lv": "aprīkojums"}},
    41: {"slug": {"en": "other-work-tools", "de": "sonstige-anbaugeraete", "ru": "prochee-navesnoe-oborudovanie", "lv": "cits-darba-aprikojums"},
         "name": {"en": "Other work tools", "de": "Sonstige Anbaugeräte", "ru": "Прочее навесное оборудование", "lv": "Cits darba aprīkojums"},
         "one": {"en": "work tool", "de": "Anbaugerät", "ru": "навесное оборудование", "lv": "darba aprīkojums"}},
}

# Item types used where the category noun is too general (set per item in data/overrides.json).
TYPES = {
    "crawler_dumper": {"en": "crawler dumper", "de": "Raupendumper", "ru": "гусеничный думпер", "lv": "kāpurķēžu pašizgāzējs"},
    "harvester": {"en": "harvester", "de": "Harvester", "ru": "харвестер", "lv": "harvesters"},
    "seed_drill": {"en": "seed drill", "de": "Sämaschine", "ru": "сеялка", "lv": "sējmašīna"},
    "land_roller": {"en": "land roller", "de": "Ackerwalze", "ru": "полевой каток", "lv": "lauku veltnis"},
    "fertiliser_spreader": {"en": "fertiliser spreader", "de": "Düngerstreuer", "ru": "разбрасыватель удобрений", "lv": "minerālmēslu izkliedētājs"},
    "combine": {"en": "combine harvester", "de": "Mähdrescher", "ru": "зерноуборочный комбайн", "lv": "graudu kombains"},
    "floor_saw": {"en": "floor saw", "de": "Fugenschneider", "ru": "швонарезчик", "lv": "šuvju griezējs"},
    "compact_track_loader": {"en": "compact track loader", "de": "Kompakt-Raupenlader", "ru": "гусеничный мини-погрузчик", "lv": "kāpurķēžu kompaktiekrāvējs"},
    "soil_compactor": {"en": "soil compactor", "de": "Walzenzug", "ru": "грунтовый каток", "lv": "grunts veltnis"},
    "tyre_roller": {"en": "pneumatic tyre roller", "de": "Gummiradwalze", "ru": "пневмоколесный каток", "lv": "pneimoriteņu veltnis"},
    "tractor_reefer": {"en": "tractor unit with refrigerated trailer", "de": "Sattelzugmaschine mit Kühlauflieger", "ru": "седельный тягач с рефрижератором", "lv": "vilcējs ar refrižeratora puspiekabi"},
    "refuse_truck": {"en": "refuse truck", "de": "Müllwagen", "ru": "мусоровоз", "lv": "atkritumu vedējs"},
    "vibro_bucket": {"en": "vibrating compaction bucket", "de": "Vibrationsverdichtungslöffel", "ru": "вибрационный уплотнительный ковш", "lv": "vibrējošs blīvēšanas kauss"},
    "mowing_bucket": {"en": "mowing bucket", "de": "Mähkorb", "ru": "ковш-косилка", "lv": "pļaušanas kauss"},
    "skid_steer_bucket": {"en": "skid steer bucket", "de": "Kompaktladerschaufel", "ru": "ковш для мини-погрузчика", "lv": "kompaktiekrāvēja kauss"},
    "four_in_one_bucket": {"en": "4-in-1 bucket", "de": "4-in-1-Schaufel", "ru": "ковш 4 в 1", "lv": "4-in-1 kauss"},
    "high_tip_bucket": {"en": "high tip bucket", "de": "Hochkippschaufel", "ru": "ковш с высокой выгрузкой", "lv": "augstās izgāšanas kauss"},
    "hammer_bracket": {"en": "hammer mounting bracket", "de": "Hammeradapter", "ru": "адаптер для гидромолота", "lv": "hidroāmura adapteris"},
    "coupler_adapter": {"en": "coupler adapter", "de": "Schnellwechsler-Adapter", "ru": "переходник для быстросъема", "lv": "sakabes adapteris"},
    "demolition_crusher": {"en": "demolition crusher", "de": "Abbruchzange", "ru": "бетонолом", "lv": "betona drupinātājs"},
    "pulverizer": {"en": "demolition pulverizer", "de": "Pulverisierer", "ru": "пульверизатор", "lv": "pulverizators"},
    "hammer": {"en": "hydraulic hammer", "de": "Hydraulikhammer", "ru": "гидромолот", "lv": "hidroāmurs"},
    "angle_broom": {"en": "angle broom", "de": "Schwenkbesen", "ru": "поворотная щетка", "lv": "grozāmā slota"},
    "clamshell": {"en": "clamshell grab", "de": "Zweischalengreifer", "ru": "двухчелюстной грейфер", "lv": "divžokļu greifers"},
    "hydraulic_clamp": {"en": "hydraulic clamp", "de": "hydraulische Klammer", "ru": "гидравлический захват", "lv": "hidrauliskais satvērējs"},
    "bale_clamp": {"en": "bale clamp", "de": "Ballenzange", "ru": "захват для тюков", "lv": "ķīpu satvērējs"},
    "screening_bucket": {"en": "screening bucket", "de": "Sieblöffel", "ru": "ковш-сепаратор", "lv": "sijāšanas kauss"},
    "crusher_bucket": {"en": "crusher bucket", "de": "Brecherlöffel", "ru": "ковш-дробилка", "lv": "drupināšanas kauss"},
    "grapple": {"en": "grapple", "de": "Sortiergreifer", "ru": "грейфер", "lv": "greifers"},
    "ripper": {"en": "ripper", "de": "Reißzahn", "ru": "рыхлитель", "lv": "irdinātājs"},
    "pallet_forks": {"en": "pallet forks", "de": "Palettengabel", "ru": "вилочный захват", "lv": "palešu dakšas"},
    "fork_tines": {"en": "forklift forks", "de": "Gabelzinken", "ru": "вилы для погрузчика", "lv": "iekrāvēja dakšas"},
    "rear_blade": {"en": "rear grader blade", "de": "Heckplanierschild", "ru": "задний отвал", "lv": "aizmugurējā lāpsta"},
    "snow_plough": {"en": "snow plough", "de": "Schneepflug", "ru": "снегоочистительный отвал", "lv": "sniega lāpsta"},
    "angle_blade": {"en": "angle blade", "de": "Schwenkschild", "ru": "поворотный отвал", "lv": "grozāmā lāpsta"},
    "tow_hook": {"en": "tow hook", "de": "Abschlepphaken", "ru": "буксирный крюк", "lv": "vilkšanas āķis"},
    "fork_jib": {"en": "fork frame with lifting jib", "de": "Gabelrahmen mit Kranarm", "ru": "вилочная рама с крановой стрелой", "lv": "dakšu rāmis ar celšanas strēli"},
}

# Specification rows, keyed by the label the old site used in English.
SPECS = {
    "Manufacturer": {"en": "Make", "de": "Hersteller", "ru": "Производитель", "lv": "Ražotājs"},
    "Model": {"en": "Model", "de": "Modell", "ru": "Модель", "lv": "Modelis"},
    "Year": {"en": "Year", "de": "Baujahr", "ru": "Год выпуска", "lv": "Izlaiduma gads"},
    "Motor hours": {"en": "Operating hours", "de": "Betriebsstunden", "ru": "Наработка", "lv": "Motorstundas"},
    "KM": {"en": "Mileage", "de": "Kilometerstand", "ru": "Пробег", "lv": "Nobraukums"},
    "Weight": {"en": "Weight", "de": "Gewicht", "ru": "Масса", "lv": "Svars"},
    "Power": {"en": "Engine power", "de": "Motorleistung", "ru": "Мощность двигателя", "lv": "Dzinēja jauda"},
    "Undercarriage": {"en": "Undercarriage remaining", "de": "Laufwerk", "ru": "Остаток ходовой части", "lv": "Ritošās daļas atlikums"},
    "Bucket m3": {"en": "Bucket capacity", "de": "Schaufelinhalt", "ru": "Объем ковша", "lv": "Kausa tilpums"},
    "Tracks width mm": {"en": "Track width", "de": "Kettenbreite", "ru": "Ширина гусениц", "lv": "Kāpurķēžu platums"},
    "Tire balance": {"en": "Tyres remaining", "de": "Reifen", "ru": "Остаток шин", "lv": "Riepu atlikums"},
    "Max Load": {"en": "Load capacity", "de": "Nutzlast", "ru": "Грузоподъемность", "lv": "Kravnesība"},
    "Payload": {"en": "Lifting capacity", "de": "Tragfähigkeit", "ru": "Грузоподъемность", "lv": "Celtspēja"},
    "Max., lifting height": {"en": "Max. lift height", "de": "Max. Hubhöhe", "ru": "Макс. высота подъема", "lv": "Maks. pacelšanas augstums"},
    "Fuel tank": {"en": "Fuel tanks", "de": "Kraftstofftanks", "ru": "Топливные баки", "lv": "Degvielas bākas"},
    "Engine capacity cm3": {"en": "Engine displacement", "de": "Hubraum", "ru": "Объем двигателя", "lv": "Motora tilpums"},
    "Hinges": {"en": "Mounting", "de": "Aufnahme", "ru": "Крепление", "lv": "Sakabe"},
    "Width": {"en": "Width", "de": "Breite", "ru": "Ширина", "lv": "Platums"},
    "Capacity": {"en": "Capacity", "de": "Inhalt", "ru": "Объем", "lv": "Tilpums"},
    "Pin hole": {"en": "Pin diameter", "de": "Bolzendurchmesser", "ru": "Диаметр пальца", "lv": "Tapas diametrs"},
    "Stick": {"en": "Stick width", "de": "Stielbreite", "ru": "Ширина рукояти", "lv": "Kāta platums"},
    "H.O.H": {"en": "Pin centre distance", "de": "Bolzenmittenabstand", "ru": "Межосевое расстояние", "lv": "Attālums starp tapu centriem"},
    "Machine weight": {"en": "Suitable for", "de": "Passend für", "ru": "Подходит для", "lv": "Paredzētā tehnika"},
    "Fraction": {"en": "Fraction", "de": "Fraktion", "ru": "Фракция", "lv": "Frakcija"},
    "Opening ( mm )": {"en": "Opening", "de": "Öffnungsweite", "ru": "Раскрытие", "lv": "Atvērums"},
    "Lenght": {"en": "Length", "de": "Länge", "ru": "Длина", "lv": "Garums"},
    "Thickness": {"en": "Thickness", "de": "Dicke", "ru": "Толщина", "lv": "Biezums"},
    "Working width": {"en": "Working width", "de": "Arbeitsbreite", "ru": "Рабочая ширина", "lv": "Darba platums"},
    "Stock number": {"en": "Stock number", "de": "Lagernummer", "ru": "Инвентарный номер", "lv": "Inventāra numurs"},
}

# Unit a bare number gets, per specification key.
SPEC_UNITS = {
    "Motor hours": "h", "KM": "km", "Weight": "kg", "Undercarriage": "%", "Tire balance": "%",
    "Bucket m3": "m3", "Tracks width mm": "mm", "Max Load": "kg", "Payload": "kg",
    "Max., lifting height": "mm", "Engine capacity cm3": "cm3", "Width": "mm", "Pin hole": "mm",
    "Stick": "mm", "H.O.H": "mm", "Opening ( mm )": "mm", "Lenght": "mm", "Thickness": "mm",
    "Working width": "mm",
}

UNITS = {
    "mm": {"ru": "мм"}, "kg": {"ru": "кг"}, "t": {"ru": "т"}, "km": {"ru": "км"}, "l": {"ru": "л"},
    "m3": {"en": "m³", "de": "m³", "lv": "m³", "ru": "м³"}, "cm3": {"en": "cm³", "de": "cm³", "lv": "cm³", "ru": "см³"},
    "m": {"ru": "м"}, "kW": {"ru": "кВт"}, "hp": {"de": "PS", "ru": "л.с.", "lv": "ZS"},
    "h": {"en": "h", "de": "Bh", "ru": "м/ч", "lv": "m/st"}, "%": {},
}

# Spec values the old site stored as English words.
VALUE_I18N = {
    "skid steer": {"en": "Skid steer", "de": "Kompaktlader", "ru": "Мини-погрузчик", "lv": "Kompaktiekrāvējs"},
    "on forks": {"en": "Fork mounted", "de": "Für Staplergabeln", "ru": "На вилы погрузчика", "lv": "Uzliekams uz dakšām"},
    "euro coupler": {"en": "Euro coupler", "de": "Euro-Aufnahme", "ru": "Евро-крепление", "lv": "Euro sakabe"},
    "bobcat / skid steer": {"en": "Bobcat / skid steer", "de": "Bobcat / Kompaktlader", "ru": "Bobcat / мини-погрузчик", "lv": "Bobcat / kompaktiekrāvējs"},
}

SPEAKS = {
    "en": {"lv": "Latvian", "ru": "Russian", "en": "English", "de": "German"},
    "de": {"lv": "Lettisch", "ru": "Russisch", "en": "Englisch", "de": "Deutsch"},
    "ru": {"lv": "латышский", "ru": "русский", "en": "английский", "de": "немецкий"},
    "lv": {"lv": "latviešu", "ru": "krievu", "en": "angļu", "de": "vācu"},
}

ROLES = {
    "Sales Manager": {"en": "Sales manager", "de": "Verkäufer", "ru": "Торговый представитель", "lv": "Tirdzniecības pārstāvis"},
    "Work tool manager": {"en": "Work tools", "de": "Verkauf Anbaugeräte", "ru": "Менеджер по навесному оборудованию", "lv": "Aprīkojuma speciālists"},
    "Director": {"en": "Director", "de": "Geschäftsführer", "ru": "Директор", "lv": "Direktors"},
}

# Interface text. Values given as tuples are plural forms: (one, other) or, for Russian, (one, few, many).
T = {
    "en": {
        "skip": "Skip to content", "menu": "Menu", "home": "Home",
        "address_short": "Klīves, Mārupe municipality, Latvia",
        "nav_stock": "All stock", "nav_about": "About us", "nav_contact": "Contact",
        "home_title": "Used construction machinery and work tools for sale | Trimen Tractors",
        "home_desc": "Used dozers, loaders, excavators, trucks, buckets and quick couplers for sale at Trimen Tractors in Klīves near Riga, Latvia. Photos, specifications and prices.",
        "home_h1": "Used construction machinery and work tools",
        "home_lead": ("Machinery dealer in Klīves near Riga, Latvia. {n} machine, truck or work tool in stock, listed with photos, specifications and price.",
                      "Machinery dealer in Klīves near Riga, Latvia. {n} machines, trucks and work tools in stock, each listed with photos, specifications and price."),
        "search_label": "Search stock", "search_all": "All categories", "search_ph": "Make, model or stock number", "search_btn": "Search",
        "call": "Call", "office": "Office", "phone": "Phone", "email": "Email", "address": "Address", "speaks": "Languages",
        "browse": "Browse by category", "count": ("{n} item", "{n} items"),
        "recent": "Recently added", "see_all": "See all stock",
        "tools_h2": "Buckets, quick couplers and attachments",
        "tools_p": ("{n} work tool in stock for excavators, wheel loaders and skid steers. Most listings include the mounting type, width, pin diameter and pin centre distance.",
                    "{n} work tools in stock for excavators, wheel loaders and skid steers. Most listings include the mounting type, width, pin diameter and pin centre distance."),
        "tools_btn": "Browse work tools",
        "about_h2": "About us",
        "about_p1": "AS Trimen Tractors sells used construction and agricultural machinery, trucks and work tools. We are based in Klīves, Mārupe municipality, west of Riga.",
        "about_p2": "Each listing shows the contact person with phone number and email. We speak Latvian, Russian, English and German.",
        "about_more": "More about us",
        "contact_h2": "Contact",
        "price_net": "excl. VAT", "price_gross": "{p} incl. 21% VAT", "price_request": "Price on request",
        "send_email": "Email", "print": "Print", "description": "Description", "specs": "Specifications",
        "seller": "Seller", "more_in": "More {cat}", "listing_id": "Listing ID", "photo": "photo {n}",
        "photos": ("{n} photo", "{n} photos"), "contact_person": "Contact person", "open_map": "Open in Google Maps",
        "enquiry_subject": "Enquiry: {title} (ID {id})", "enquiry_body": "Hello,\n\nI am interested in {title}.\n{url}\n\n",
        "prev": "Previous photo", "next": "Next photo", "close": "Close",
        "f_search": "Search", "f_cat": "Category", "f_make": "Make", "f_all": "All", "f_hinge": "Mounting",
        "f_width": "Width, mm", "f_from": "from", "f_to": "to", "f_sort": "Sort", "f_reset": "Clear filters",
        "s_new": "Newest first", "s_price_asc": "Price, low to high", "s_price_desc": "Price, high to low",
        "s_year": "Year, newest first", "s_width": "Width, smallest first",
        "results": ("{n} item", "{n} items"), "no_results": "Nothing matches these filters.",
        "stock_title": "All stock: machinery, trucks and work tools | Trimen Tractors", "stock_h1": "All stock",
        "stock_desc": "All {n} items for sale at Trimen Tractors: used construction and farm machinery, trucks, buckets and quick couplers, with photos and prices.",
        "about_title": "About us and contact | Trimen Tractors", "about_h1": "About Trimen Tractors",
        "about_desc": "AS Trimen Tractors, used machinery dealer in Klīves, Mārupe municipality, Latvia. Address, phone numbers, sales team and company details.",
        "about_page": [
            "AS Trimen Tractors sells used construction machinery, agricultural machinery, trucks and work tools for excavators and loaders.",
            "We are in Klīves, Mārupe municipality, west of Riga. Everything we have for sale is listed on this website with photos, specifications and prices with and without VAT.",
            "Each listing names the person responsible for it. Call or email them directly; between us we speak Latvian, Russian, English and German.",
        ],
        "company": "Company", "team_h2": "Sales team", "company_h2": "Company details", "reg_no": "Registration No.", "vat_no": "VAT No.",
        "bank": "Bank", "gallery_h2": "Photos", "follow": "Follow us",
        "footer_vat": "Prices in EUR. Net prices exclude VAT; gross prices include 21% Latvian VAT.",
        "cat_title": "{h1} for sale | Trimen Tractors",
        "cat_desc": "{h1} for sale at Trimen Tractors, Latvia: {n} in stock{makes}. Photos, specifications and prices excl. VAT.",
        "makes": ", including {list}",
        "intro_machine": "{h1} from our stock in Klīves, Latvia. Each listing has photos, the main specifications and the price without VAT.",
        "intro_tool": "{h1} in stock in Klīves, Latvia. Where we have them, listings show the width, mounting type and pin measurements.",
        "verachtert": "More work tools: Verachtert stock", "categories": "Categories", "all_in": "All {cat}",
        "nf_title": "Page not found", "nf_text": "This page does not exist or the item has been sold.",
        "prod_desc_price": "Price {p} excl. VAT.",
    },
    "de": {
        "skip": "Zum Inhalt springen", "menu": "Menü", "home": "Startseite",
        "address_short": "Klīves, Bezirk Mārupe, Lettland",
        "nav_stock": "Alle Angebote", "nav_about": "Über uns", "nav_contact": "Kontakt",
        "home_title": "Gebrauchte Baumaschinen und Anbaugeräte kaufen | Trimen Tractors",
        "home_desc": "Gebrauchte Planierraupen, Radlader, Bagger, Lkw, Tieflöffel und Schnellwechsler bei Trimen Tractors in Klīves bei Riga, Lettland. Mit Fotos, technischen Daten und Preisen.",
        "home_h1": "Gebrauchte Baumaschinen und Anbaugeräte",
        "home_lead": ("Maschinenhändler in Klīves bei Riga, Lettland. {n} Angebot auf Lager, mit Fotos, technischen Daten und Preis.",
                      "Maschinenhändler in Klīves bei Riga, Lettland. {n} Maschinen, Lkw und Anbaugeräte auf Lager, jeweils mit Fotos, technischen Daten und Preis."),
        "search_label": "Angebote durchsuchen", "search_all": "Alle Kategorien", "search_ph": "Marke, Modell oder Lagernummer", "search_btn": "Suchen",
        "call": "Anrufen", "office": "Büro", "phone": "Telefon", "email": "E-Mail", "address": "Adresse", "speaks": "Sprachen",
        "browse": "Kategorien", "count": ("{n} Angebot", "{n} Angebote"),
        "recent": "Neu im Angebot", "see_all": "Alle Angebote ansehen",
        "tools_h2": "Löffel, Schnellwechsler und Anbaugeräte",
        "tools_p": ("{n} Anbaugerät für Bagger, Radlader und Kompaktlader auf Lager. Bei den meisten Angeboten sind Aufnahme, Breite, Bolzendurchmesser und Bolzenmittenabstand angegeben.",
                    "{n} Anbaugeräte für Bagger, Radlader und Kompaktlader auf Lager. Bei den meisten Angeboten sind Aufnahme, Breite, Bolzendurchmesser und Bolzenmittenabstand angegeben."),
        "tools_btn": "Anbaugeräte ansehen",
        "about_h2": "Über uns",
        "about_p1": "Die AS Trimen Tractors verkauft gebrauchte Bau- und Landmaschinen, Lkw und Anbaugeräte. Unser Standort ist Klīves im Bezirk Mārupe, westlich von Riga.",
        "about_p2": "Bei jedem Angebot finden Sie den zuständigen Ansprechpartner mit Telefonnummer und E-Mail. Wir sprechen Lettisch, Russisch, Englisch und Deutsch.",
        "about_more": "Mehr über uns",
        "contact_h2": "Kontakt",
        "price_net": "zzgl. MwSt.", "price_gross": "{p} inkl. 21 % MwSt.", "price_request": "Preis auf Anfrage",
        "send_email": "E-Mail", "print": "Drucken", "description": "Beschreibung", "specs": "Technische Daten",
        "seller": "Verkäufer", "more_in": "Weitere Angebote: {cat}", "listing_id": "Angebots-Nr.", "photo": "Foto {n}",
        "photos": ("{n} Foto", "{n} Fotos"), "contact_person": "Ansprechpartner", "open_map": "In Google Maps öffnen",
        "enquiry_subject": "Anfrage: {title} (Nr. {id})", "enquiry_body": "Guten Tag,\n\nich interessiere mich für folgendes Angebot: {title}.\n{url}\n\n",
        "prev": "Vorheriges Foto", "next": "Nächstes Foto", "close": "Schließen",
        "f_search": "Suche", "f_cat": "Kategorie", "f_make": "Marke", "f_all": "Alle", "f_hinge": "Aufnahme",
        "f_width": "Breite, mm", "f_from": "von", "f_to": "bis", "f_sort": "Sortieren", "f_reset": "Filter zurücksetzen",
        "s_new": "Neueste zuerst", "s_price_asc": "Preis aufsteigend", "s_price_desc": "Preis absteigend",
        "s_year": "Baujahr, neueste zuerst", "s_width": "Breite aufsteigend",
        "results": ("{n} Angebot", "{n} Angebote"), "no_results": "Keine Angebote für diese Auswahl.",
        "stock_title": "Alle Angebote: Maschinen, Lkw und Anbaugeräte | Trimen Tractors", "stock_h1": "Alle Angebote",
        "stock_desc": "Alle {n} Angebote von Trimen Tractors: gebrauchte Bau- und Landmaschinen, Lkw, Löffel und Schnellwechsler mit Fotos und Preisen.",
        "about_title": "Über uns und Kontakt | Trimen Tractors", "about_h1": "Über Trimen Tractors",
        "about_desc": "AS Trimen Tractors, Händler für gebrauchte Maschinen in Klīves, Bezirk Mārupe, Lettland. Adresse, Telefonnummern, Ansprechpartner und Firmendaten.",
        "about_page": [
            "Die AS Trimen Tractors verkauft gebrauchte Baumaschinen, Landmaschinen, Lkw sowie Anbaugeräte für Bagger und Lader.",
            "Unser Standort ist Klīves im Bezirk Mārupe, westlich von Riga. Alle Angebote stehen auf dieser Website mit Fotos, technischen Daten und Preisen mit und ohne MwSt.",
            "Bei jedem Angebot steht der zuständige Ansprechpartner. Sie erreichen ihn direkt per Telefon oder E-Mail; wir sprechen Lettisch, Russisch, Englisch und Deutsch.",
        ],
        "company": "Firma", "team_h2": "Ansprechpartner", "company_h2": "Firmendaten", "reg_no": "Registernummer", "vat_no": "USt-IdNr.",
        "bank": "Bank", "gallery_h2": "Fotos", "follow": "Folgen Sie uns",
        "footer_vat": "Preise in EUR. Nettopreise zzgl. MwSt., Bruttopreise inkl. 21 % lettischer MwSt.",
        "cat_title": "{h1} kaufen | Trimen Tractors",
        "cat_desc": "{h1} bei Trimen Tractors, Lettland: {n} auf Lager{makes}. Fotos, technische Daten und Nettopreise.",
        "makes": ", u. a. {list}",
        "intro_machine": "{h1} aus unserem Bestand in Klīves, Lettland. Jedes Angebot mit Fotos, den wichtigsten technischen Daten und Nettopreis.",
        "intro_tool": "{h1} aus unserem Bestand in Klīves, Lettland. Soweit bekannt, sind Breite, Aufnahme und Bolzenmaße angegeben.",
        "verachtert": "Weitere Anbaugeräte: Lager von Verachtert", "categories": "Kategorien", "all_in": "Alle: {cat}",
        "nf_title": "Seite nicht gefunden", "nf_text": "Diese Seite gibt es nicht oder das Angebot ist bereits verkauft.",
        "prod_desc_price": "Preis {p} zzgl. MwSt.",
    },
    "ru": {
        "skip": "Перейти к содержанию", "menu": "Меню", "home": "Главная",
        "address_short": "Кливес, Марупский край, Латвия",
        "nav_stock": "Все предложения", "nav_about": "О нас", "nav_contact": "Контакты",
        "home_title": "Б/у спецтехника и навесное оборудование | Trimen Tractors",
        "home_desc": "Б/у бульдозеры, погрузчики, экскаваторы, грузовики, ковши и быстросъемы в продаже у Trimen Tractors под Ригой, Латвия. Фото, характеристики и цены.",
        "home_h1": "Б/у спецтехника и навесное оборудование",
        "home_lead": ("Продаем б/у технику под Ригой, Латвия. В наличии {n} позиция: техника, грузовики и навесное оборудование. В каждом объявлении есть фото, характеристики и цена.",
                      "Продаем б/у технику под Ригой, Латвия. В наличии {n} позиции: техника, грузовики и навесное оборудование. В каждом объявлении есть фото, характеристики и цена.",
                      "Продаем б/у технику под Ригой, Латвия. В наличии {n} позиций: техника, грузовики и навесное оборудование. В каждом объявлении есть фото, характеристики и цена."),
        "search_label": "Поиск по каталогу", "search_all": "Все категории", "search_ph": "Марка, модель или инвентарный номер", "search_btn": "Найти",
        "call": "Позвонить", "office": "Офис", "phone": "Телефон", "email": "Эл. почта", "address": "Адрес", "speaks": "Языки",
        "browse": "Категории", "count": ("{n} позиция", "{n} позиции", "{n} позиций"),
        "recent": "Новые поступления", "see_all": "Все предложения",
        "tools_h2": "Ковши, быстросъемы и навесное оборудование",
        "tools_p": ("Навесное оборудование для экскаваторов, фронтальных и мини-погрузчиков: в наличии {n} позиция. В большинстве объявлений указаны тип крепления, ширина, диаметр пальца и межосевое расстояние.",
                    "Навесное оборудование для экскаваторов, фронтальных и мини-погрузчиков: в наличии {n} позиции. В большинстве объявлений указаны тип крепления, ширина, диаметр пальца и межосевое расстояние.",
                    "Навесное оборудование для экскаваторов, фронтальных и мини-погрузчиков: в наличии {n} позиций. В большинстве объявлений указаны тип крепления, ширина, диаметр пальца и межосевое расстояние."),
        "tools_btn": "Смотреть навесное оборудование",
        "about_h2": "О нас",
        "about_p1": "AS Trimen Tractors продает б/у строительную и сельскохозяйственную технику, грузовики и навесное оборудование. Мы находимся в поселке Кливес Марупского края, к западу от Риги.",
        "about_p2": "В каждом объявлении указано контактное лицо с телефоном и электронной почтой. Мы говорим на латышском, русском, английском и немецком.",
        "about_more": "Подробнее о нас",
        "contact_h2": "Контакты",
        "price_net": "без НДС", "price_gross": "{p} с НДС 21 %", "price_request": "Цена по запросу",
        "send_email": "Написать", "print": "Печать", "description": "Описание", "specs": "Характеристики",
        "seller": "Продавец", "more_in": "Еще в разделе «{cat}»", "listing_id": "Номер объявления", "photo": "фото {n}",
        "photos": ("{n} фото", "{n} фото", "{n} фото"), "contact_person": "Контактное лицо", "open_map": "Открыть в Google Maps",
        "enquiry_subject": "Запрос: {title} (№ {id})", "enquiry_body": "Здравствуйте!\n\nМеня интересует объявление: {title}.\n{url}\n\n",
        "prev": "Предыдущее фото", "next": "Следующее фото", "close": "Закрыть",
        "f_search": "Поиск", "f_cat": "Категория", "f_make": "Марка", "f_all": "Все", "f_hinge": "Крепление",
        "f_width": "Ширина, мм", "f_from": "от", "f_to": "до", "f_sort": "Сортировка", "f_reset": "Сбросить фильтры",
        "s_new": "Сначала новые", "s_price_asc": "Сначала дешевле", "s_price_desc": "Сначала дороже",
        "s_year": "Год выпуска, сначала новые", "s_width": "Ширина, по возрастанию",
        "results": ("Найдена {n} позиция", "Найдено {n} позиции", "Найдено {n} позиций"), "no_results": "По этим условиям ничего не найдено.",
        "stock_title": "Все предложения: техника, грузовики и навесное оборудование | Trimen Tractors", "stock_h1": "Все предложения",
        "stock_desc": "Все предложения Trimen Tractors ({n}): б/у строительная и сельхозтехника, грузовики, ковши и быстросъемы с фото и ценами.",
        "about_title": "О компании и контакты | Trimen Tractors", "about_h1": "О компании Trimen Tractors",
        "about_desc": "AS Trimen Tractors, продажа б/у техники под Ригой, Марупский край, Латвия. Адрес, телефоны, менеджеры и реквизиты компании.",
        "about_page": [
            "AS Trimen Tractors продает б/у строительную и сельскохозяйственную технику, грузовики и навесное оборудование для экскаваторов и погрузчиков.",
            "Мы находимся в поселке Кливес Марупского края, к западу от Риги. Все, что мы продаем, есть на этом сайте: с фото, характеристиками и ценами с НДС и без.",
            "В каждом объявлении указан ответственный менеджер. Звоните или пишите ему напрямую; мы говорим на латышском, русском, английском и немецком.",
        ],
        "company": "Компания", "team_h2": "Менеджеры", "company_h2": "Реквизиты", "reg_no": "Рег. номер", "vat_no": "Номер плательщика НДС",
        "bank": "Банк", "gallery_h2": "Фото", "follow": "Мы в соцсетях",
        "footer_vat": "Цены в евро. Цена нетто без НДС, цена брутто с НДС Латвии 21 %.",
        "cat_title": "{h1} в продаже | Trimen Tractors",
        "cat_desc": "{h1} в продаже у Trimen Tractors, Латвия: в наличии {n}{makes}. Фото, характеристики и цены без НДС.",
        "makes": ", в том числе {list}",
        "intro_machine": "{h1} в наличии на нашей площадке под Ригой. В каждом объявлении есть фото, основные характеристики и цена без НДС.",
        "intro_tool": "{h1} в наличии на нашей площадке под Ригой. Где известно, указаны ширина, тип крепления и размеры пальцев.",
        "verachtert": "Больше навесного оборудования: склад Verachtert", "categories": "Категории", "all_in": "Все: {cat}",
        "nf_title": "Страница не найдена", "nf_text": "Такой страницы нет или техника уже продана.",
        "prod_desc_price": "Цена {p} без НДС.",
    },
    "lv": {
        "skip": "Pāriet uz saturu", "menu": "Izvēlne", "home": "Sākums",
        "address_short": "Klīves, Mārupes novads",
        "nav_stock": "Visi piedāvājumi", "nav_about": "Par mums", "nav_contact": "Kontakti",
        "home_title": "Lietota būvtehnika un darba aprīkojums | Trimen Tractors",
        "home_desc": "Lietoti buldozeri, iekrāvēji, ekskavatori, kravas auto, kausi un ātrās sakabes. Trimen Tractors Klīvēs pie Rīgas. Fotogrāfijas, tehniskie dati un cenas.",
        "home_h1": "Lietota būvtehnika un darba aprīkojums",
        "home_lead": ("Tehnikas tirdzniecība Klīvēs pie Rīgas. Šobrīd pieejams {n} piedāvājums: tehnika, kravas auto un darba aprīkojums. Katram sludinājumam ir fotogrāfijas, tehniskie dati un cena.",
                      "Tehnikas tirdzniecība Klīvēs pie Rīgas. Šobrīd pieejami {n} piedāvājumi: tehnika, kravas auto un darba aprīkojums. Katram sludinājumam ir fotogrāfijas, tehniskie dati un cena."),
        "search_label": "Meklēt piedāvājumos", "search_all": "Visas kategorijas", "search_ph": "Ražotājs, modelis vai inventāra numurs", "search_btn": "Meklēt",
        "call": "Zvanīt", "office": "Birojs", "phone": "Tālrunis", "email": "E-pasts", "address": "Adrese", "speaks": "Valodas",
        "browse": "Kategorijas", "count": ("{n} piedāvājums", "{n} piedāvājumi"),
        "recent": "Jaunākie piedāvājumi", "see_all": "Visi piedāvājumi",
        "tools_h2": "Kausi, ātrās sakabes un darba aprīkojums",
        "tools_p": ("Darba aprīkojums ekskavatoriem, frontālajiem un kompaktajiem iekrāvējiem: pieejams {n} piedāvājums. Vairumam sludinājumu norādīts sakabes veids, platums, tapas diametrs un attālums starp tapu centriem.",
                    "Darba aprīkojums ekskavatoriem, frontālajiem un kompaktajiem iekrāvējiem: pieejami {n} piedāvājumi. Vairumam sludinājumu norādīts sakabes veids, platums, tapas diametrs un attālums starp tapu centriem."),
        "tools_btn": "Skatīt darba aprīkojumu",
        "about_h2": "Par mums",
        "about_p1": "AS Trimen Tractors pārdod lietotu būvtehniku, lauksaimniecības tehniku, kravas auto un darba aprīkojumu. Atrodamies Klīvēs, Mārupes novadā, uz rietumiem no Rīgas.",
        "about_p2": "Katrā sludinājumā norādīta kontaktpersona ar tālruni un e-pastu. Runājam latviski, krieviski, angliski un vāciski.",
        "about_more": "Vairāk par mums",
        "contact_h2": "Kontakti",
        "price_net": "bez PVN", "price_gross": "{p} ar PVN 21 %", "price_request": "Cena pēc pieprasījuma",
        "send_email": "Rakstīt", "print": "Drukāt", "description": "Apraksts", "specs": "Tehniskie dati",
        "seller": "Pārdevējs", "more_in": "Citi piedāvājumi: {cat}", "listing_id": "Sludinājuma Nr.", "photo": "foto {n}",
        "photos": ("{n} foto", "{n} foto"), "contact_person": "Kontaktpersona", "open_map": "Atvērt Google Maps",
        "enquiry_subject": "Pieprasījums: {title} (Nr. {id})", "enquiry_body": "Labdien!\n\nMani interesē sludinājums: {title}.\n{url}\n\n",
        "prev": "Iepriekšējais foto", "next": "Nākamais foto", "close": "Aizvērt",
        "f_search": "Meklēt", "f_cat": "Kategorija", "f_make": "Ražotājs", "f_all": "Visi", "f_hinge": "Sakabe",
        "f_width": "Platums, mm", "f_from": "no", "f_to": "līdz", "f_sort": "Kārtot", "f_reset": "Notīrīt filtrus",
        "s_new": "Jaunākie vispirms", "s_price_asc": "Lētākie vispirms", "s_price_desc": "Dārgākie vispirms",
        "s_year": "Izlaiduma gads, jaunākie vispirms", "s_width": "Platums augošā secībā",
        "results": ("Atrasts {n} piedāvājums", "Atrasti {n} piedāvājumi"), "no_results": "Pēc šiem kritērijiem nekas netika atrasts.",
        "stock_title": "Visi piedāvājumi: tehnika, kravas auto un aprīkojums | Trimen Tractors", "stock_h1": "Visi piedāvājumi",
        "stock_desc": "Visi Trimen Tractors piedāvājumi ({n}): lietota būvtehnika un lauksaimniecības tehnika, kravas auto, kausi un ātrās sakabes ar foto un cenām.",
        "about_title": "Par mums un kontakti | Trimen Tractors", "about_h1": "Par Trimen Tractors",
        "about_desc": "AS Trimen Tractors, lietotas tehnikas tirdzniecība Klīvēs, Mārupes novadā. Adrese, tālruņi, kontaktpersonas un rekvizīti.",
        "about_page": [
            "AS Trimen Tractors pārdod lietotu būvtehniku, lauksaimniecības tehniku, kravas auto un darba aprīkojumu ekskavatoriem un iekrāvējiem.",
            "Atrodamies Klīvēs, Mārupes novadā, uz rietumiem no Rīgas. Viss, ko pārdodam, ir šajā mājaslapā ar fotogrāfijām, tehniskajiem datiem un cenām ar un bez PVN.",
            "Katrā sludinājumā norādīts par to atbildīgais darbinieks. Zvaniet vai rakstiet viņam tieši; runājam latviski, krieviski, angliski un vāciski.",
        ],
        "company": "Uzņēmums", "team_h2": "Kontaktpersonas", "company_h2": "Rekvizīti", "reg_no": "Reģ. Nr.", "vat_no": "PVN maksātāja Nr.",
        "bank": "Banka", "gallery_h2": "Foto", "follow": "Seko mums",
        "footer_vat": "Cenas norādītas EUR. Neto cena bez PVN, bruto cena ar 21 % PVN.",
        "cat_title": "{h1} pārdošanā | Trimen Tractors",
        "cat_desc": "{h1} pārdošanā, Trimen Tractors: pieejami {n}{makes}. Fotogrāfijas, tehniskie dati un cenas bez PVN.",
        "makes": ", tostarp {list}",
        "intro_machine": "{h1} no mūsu laukuma Klīvēs. Katram sludinājumam ir fotogrāfijas, galvenie tehniskie dati un cena bez PVN.",
        "intro_tool": "{h1} no mūsu laukuma Klīvēs. Ja zināms, sludinājumā norādīts platums, sakabes veids un tapu izmēri.",
        "verachtert": "Vairāk darba aprīkojuma: Verachtert noliktava", "categories": "Kategorijas", "all_in": "Visi: {cat}",
        "nf_title": "Lapa nav atrasta", "nf_text": "Šādas lapas nav vai tehnika jau ir pārdota.",
        "prod_desc_price": "Cena {p} bez PVN.",
    },
}
